# prefix ctr+space
unbind C-b
set -g prefix C-Space
bind C-Space send-prefix

# split panes using | and -
bind | split-window -h
bind - split-window -v
unbind '"'
unbind %
## use current directory for split windows
bind | split-window -h -c "#{pane_current_path}"
bind - split-window -v -c "#{pane_current_path}"

# mouse
set-option -g mouse on
set -g mouse on
set-window-option -g mouse on

# switch panes using Alt-arrow without prefix
bind -n M-Left select-pane -L
bind -n M-Right select-pane -R
bind -n M-Up select-pane -U
bind -n M-Down select-pane -D

# status bar
set -g status-left ''
set -g status-right ''
set -g status-bg white

# start windows and panes index at 1, not 0.
set -g base-index 1
set -g pane-base-index 1
set -g renumber-windows 1

# pane
set -g pane-border-lines single 
set -g pane-active-border-style "fg=default"
set -g pane-border-style "fg=default"

# window
set -g automatic-rename on
set -g automatic-rename-format "#{b:pane_current_path}" 

# misc
set -g extended-keys on
set -g extended-keys-format csi-u
set -g allow-passthrough on
